WINDOW_HEIGHT = 800
WINDOW_WIDTH = 800
CANVAS_HEIGHT: int = 400

NODE_WIDTH = 280
NODE_HEIGHT = 280

CHILD_NODE_Y_OFFSET = 420
CHILD_NODE_LEFT_X_OFFSET = -260
CHILD_NODE_RIGHT_X_OFFSET = 260

PLUS_BUTTON_WIDTH = 22

# made up estimates - can be changed
GAME_TREE_WIDTH = 3000
TREE_Y_OFFSET = 50

# ai panel
AI_PANEL_WIDTH = 300

# for connector lines
LINE_WIDTH = 2